# Generated by Django 2.2.7 on 2019-11-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytul_PL', models.CharField(max_length=45)),
                ('Tytul_ENG', models.CharField(max_length=45)),
                ('Rok_premiery', models.DateTimeField(verbose_name='data publikacji')),
                ('Czas_trwania', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zaliczka', models.CharField(max_length=45)),
                ('Doplata', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('PESEL', models.CharField(max_length=11)),
                ('Ulica', models.CharField(max_length=45)),
                ('Misasto', models.CharField(max_length=45)),
                ('Telefon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Platnosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zaliczka', models.CharField(max_length=45)),
                ('Doplata', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('PESEL', models.CharField(max_length=11)),
                ('Wiek', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rejestr_wypozyczen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_wypozyczenia', models.DateTimeField(verbose_name='data wypozyczenia')),
                ('Data_zwrotu', models.DateTimeField(verbose_name='data zwrotu')),
                ('filmy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmowLegit.Filmy')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmowLegit.Klient')),
                ('platnosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmowLegit.Platnosci')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmowLegit.Pracownik')),
            ],
        ),
        migrations.AddField(
            model_name='filmy',
            name='gatunek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmowLegit.Gatunek'),
        ),
        migrations.AddField(
            model_name='filmy',
            name='rezyser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmowLegit.Rezyser'),
        ),
    ]
